[package]
name = "agplatform"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"
homepage = "https://github.com/agnesoft/agnesoft"
repository = "https://github.com/agnesoft/agnesoft"
documentation = "https://github.com/agnesoft/agnesoft"
readme = "../README.md"
description = "Agnesoft Platform"
keywords = ["build", "test"]
categories = ["development-tools"]

[lib]
