name: agnesoft

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]

env:
  CHECKOUT_ACTION: &CHECKOUT_ACTION actions/checkout@v7
  CODECOV_ACTION: &CODECOV_ACTION codecov/codecov-action@v7
  DEPLOY_PAGE_ACTION: &DEPLOY_PAGE_ACTION actions/deploy-pages@v5
  SCRIPT_ACTION: &SCRIPT_ACTION actions/github-script@v9
  RUST_SETUP_ACTION: &RUST_SETUP_ACTION actions-rust-lang/setup-rust-toolchain@v1
  UPLOAD_PAGES_ARTIFACT_ACTION: &UPLOAD_PAGES_ARTIFACT_ACTION actions/upload-pages-artifact@v5
  IS_PR: &IS_PR ${{ github.event_name == 'pull_request' }}
  IS_PR_OR_MAIN: &IS_PR_OR_MAIN ${{ github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main') }}
  IS_MAIN: &IS_MAIN ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

jobs:
  title_check:
    runs-on: ubuntu-latest
    if: *IS_PR
    steps:
      - uses: *CHECKOUT_ACTION
      - uses: *SCRIPT_ACTION
        with:
          script: |
            const script = require('./.github/workflows/title_check.js')
            await script({github, context, core})

  build:
    if: *IS_PR_OR_MAIN
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: coverage-report-html
      url: ${{ steps.coverage-report-pages.outputs.page_url }}
    steps:
      - uses: *CHECKOUT_ACTION
      - uses: *RUST_SETUP_ACTION
        with:
          components: rustfmt,clippy
      - if: *IS_PR
        run: cargo fmt --check
      - if: *IS_PR
        run: cargo clippy --all-targets --all-features -- -D warnings
      - if: *IS_PR
        run: cargo test --all-features --doc
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: rustup component add llvm-tools-preview
      - run: cargo llvm-cov --all-features --no-report
      - run: cargo llvm-cov report --show-missing-lines
      - run: cargo llvm-cov report --codecov --output-path codecov.info
      - run: cargo llvm-cov report --html
      - id: coverage-report-html
        uses: *UPLOAD_PAGES_ARTIFACT_ACTION
        with:
          name: coverage-report-html
          path: target/llvm-cov/html
      - if: *IS_PR
        id: coverage-report-pages
        uses: *DEPLOY_PAGE_ACTION
        with:
          artifact_name: coverage-report-html
      - uses: *CODECOV_ACTION
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.info
